<template>
  <div v-if="project" class="analysis-view">
    <header class="top-nav">
      <button @click="goToProject" class="btn icon-btn">
        <span class="material-icons">arrow_back</span>
        Back to Project
      </button>
      <h1>{{ project.title }} - Analysis</h1>
      <div class="placeholder-div"></div>
    </header>

    <div class="analysis-content">
      <div class="analysis-container">
        <div class="toolbar top-toolbar">
          <span class="toolbar-label">Mental Space Analysis</span>
        </div>

        <div class="analysis-text markdown-rendered" v-html="renderedAnalysis"></div>

        <div class="toolbar bottom-toolbar">
          <span class="toolbar-caption">generated by AI</span>
          <div class="toolbar-buttons">
            <button @click="refreshAnalysis" class="btn icon-btn">
              <span class="material-icons">refresh</span>
              Refresh
            </button>
            <button @click="copyAnalysis" class="btn icon-btn">
              <span class="material-icons">content_copy</span>
              Copy
            </button>
          </div>
        </div>
      </div>
    </div>

    <div v-if="toolbarMessage" class="toolbar-message">{{ toolbarMessage }}</div>
  </div>
  <div v-else class="loading">Loading analysis...</div>
</template>

<script>
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import axios from 'axios';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

export default {
  name: 'AnalysisView',
  setup() {
    const route = useRoute();
    const router = useRouter();
    const project = ref(null);
    const toolbarMessage = ref('');

    const renderedAnalysis = computed(() => {
      if (project.value?.analysis) {
        const rawHtml = marked(project.value.analysis);
        return DOMPurify.sanitize(rawHtml);
      }
      return '';
    });

    const fetchProjectAnalysis = async () => {
      try {
        const projectId = route.params.id;
        const token = localStorage.getItem('token');
        const response = await axios.get(`${import.meta.env.VITE_API_URL}/projects/${projectId}`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        project.value = response.data;
      } catch (error) {
        console.error('Error fetching project analysis:', error);
      }
    };

    const refreshAnalysis = async () => {
      await fetchProjectAnalysis();
      showToolbarMessage('Analysis refreshed!');
    };

    const copyAnalysis = () => {
      navigator.clipboard.writeText(project.value.analysis)
        .then(() => showToolbarMessage('Copied to clipboard!'))
        .catch(() => showToolbarMessage('Failed to copy.'));
    };

    const showToolbarMessage = (message) => {
      toolbarMessage.value = message;
      setTimeout(() => {
        toolbarMessage.value = '';
      }, 3000);
    };

    const goToProject = () => {
      router.push(`/project/${project.value.id}`);
    };

    onMounted(fetchProjectAnalysis);

    return {
      project,
      renderedAnalysis,
      toolbarMessage,
      refreshAnalysis,
      copyAnalysis,
      goToProject
    };
  }
};
</script>

<style scoped>
.analysis-view {
  display: flex;
  flex-direction: column;
  height: 100vh;
  font-family: Arial, sans-serif;
}

.top-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background-color: #4CAF50;
  color: white;
}

.top-nav h1 {
  margin: 0;
  font-size: 1.5rem;
}

.placeholder-div {
  width: 100px; /* Regola questa larghezza in base alla larghezza del pulsante "Back to Project" */
}

.analysis-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 1rem;
}

.analysis-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background-color: #ffffff;
  border: 1px solid #ddd;
  border-radius: 8px;
}

.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 1rem;
  background-color: #f0f0f0;
}

.bottom-toolbar {
  margin-top: auto;
}

.toolbar-buttons {
  display: flex;
  gap: 0.5rem;
}

.btn {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  transition: background-color 0.3s;
}

.icon-btn {
  background-color: #4CAF50;
  color: white;
}

.icon-btn:hover {
  background-color: #45a049;
}

.analysis-text {
  flex: 1;
  padding: 1rem;
  overflow-y: auto;
  font-size: 1rem;
  line-height: 1.6;
}

.loading {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-size: 1.2rem;
  color: #666;
}

.toolbar-message {
  position: fixed;
  bottom: 1rem;
  left: 50%;
  transform: translateX(-50%);
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  font-size: 0.9rem;
  z-index: 1000;
}

.markdown-rendered {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  text-align: left;
}

.markdown-rendered * {
  text-align: left;
}
</style>