<template>
  <div v-if="project" class="analysis-view">
    <header class="top-nav">
      <button @click="goToProject" class="btn icon-btn">
        <span class="material-icons">arrow_back</span>
        Back to Project
      </button>
      <h1>{{ project.title }} - Analysis</h1>
      <div class="placeholder-div"></div>
    </header>

    <div class="analysis-content">
      <div class="analysis-container">
        <div class="toolbar top-toolbar">
          <span class="toolbar-label">Mental Space Analysis</span>
        </div>

        <div v-if="isLoading" class="loading-spinner">
          <div class="spinner"></div>
          <p>Generating analysis...</p>
        </div>

        <div v-else class="analysis-text markdown-rendered" v-html="renderedAnalysis"></div>

        <div class="toolbar bottom-toolbar">
          <span class="toolbar-caption">generated by AI</span>
          <div class="toolbar-buttons">
            <button @click="refreshAnalysis" class="btn icon-btn" :disabled="isLoading">
              <span class="material-icons">refresh</span>
              Refresh
            </button>
            <button @click="copyAnalysis" class="btn icon-btn" :disabled="isLoading">
              <span class="material-icons">content_copy</span>
              Copy
            </button>
          </div>
        </div>
      </div>
    </div>

    <div v-if="toolbarMessage" class="toolbar-message">{{ toolbarMessage }}</div>
  </div>
  <div v-else-if="isLoading" class="loading">
    <div class="spinner"></div>
    <p>Generating the analysis...</p>
  </div>
  <div v-else class="loading">Error loading project</div>
</template>

<script>
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import axios from 'axios';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

export default {
  name: 'AnalysisView',
  setup() {
    const route = useRoute();
    const router = useRouter();
    const project = ref(null);
    const toolbarMessage = ref('');
    const isLoading = ref(true);

    const renderedAnalysis = computed(() => {
      if (project.value?.analysis) {
        const rawHtml = marked(project.value.analysis);
        return DOMPurify.sanitize(rawHtml);
      }
      return '';
    });

    const fetchProjectAnalysis = async () => {
      try {
        const projectId = route.params.id;
        const token = localStorage.getItem('token');
        const response = await axios.get(`${import.meta.env.VITE_API_URL}/projects/${projectId}`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        project.value = response.data;

        if (project.value.generate_analysis) {
          await generateAnalysis();
        } else {
          isLoading.value = false;
        }
      } catch (error) {
        console.error('Error fetching project analysis:', error);
        isLoading.value = false;
      }
    };

    const generateAnalysis = async () => {
      try {
        isLoading.value = true;
        const token = localStorage.getItem('token');
        const response = await axios.post(`${import.meta.env.VITE_API_URL}/projects/${project.value.id}/query-implicit-knowledge`, {}, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        // Assumendo che la risposta contenga l'analisi generata
        project.value.analysis = response.data.data;

        // Aggiorna il progetto nel backend con la nuova analisi
        await updateProjectAnalysis();

        isLoading.value = false;
      } catch (error) {
        console.error('Error generating analysis:', error);
        isLoading.value = false;
        showToolbarMessage('Error generating analysis');
      }
    };

    const updateProjectAnalysis = async () => {
      try {
        const token = localStorage.getItem('token');
        await axios.put(`${import.meta.env.VITE_API_URL}/projects/${project.value.id}`, {
          analysis: project.value.analysis,
          generate_analysis: false
        }, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
      } catch (error) {
        console.error('Error updating project analysis:', error);
      }
    };

    const refreshAnalysis = async () => {
    try {
      isLoading.value = true;
      await fetchProjectAnalysis();
      showToolbarMessage('Analysis refreshed!');
    } catch (error) {
      console.error('Error refreshing analysis:', error);
      showToolbarMessage('Error refreshing analysis');
    } finally {
      isLoading.value = false;
    }
  };

    const copyAnalysis = () => {
      navigator.clipboard.writeText(project.value.analysis)
        .then(() => showToolbarMessage('Copied to clipboard!'))
        .catch(() => showToolbarMessage('Failed to copy.'));
    };

    const showToolbarMessage = (message) => {
      toolbarMessage.value = message;
      setTimeout(() => {
        toolbarMessage.value = '';
      }, 3000);
    };

    const goToProject = () => {
      router.push(`/project/${project.value.id}`);
    };

    onMounted(fetchProjectAnalysis);

    return {
      project,
      renderedAnalysis,
      toolbarMessage,
      isLoading,
      refreshAnalysis,
      copyAnalysis,
      goToProject
    };
  }
};
</script>


<style scoped>
.analysis-view {
  display: flex;
  flex-direction: column;
  height: 100vh;
  font-family: Arial, sans-serif;
}

.top-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background-color: #4CAF50;
  color: white;
}

.top-nav h1 {
  margin: 0;
  font-size: 1.5rem;
}

.placeholder-div {
  width: 100px; /* Regola questa larghezza in base alla larghezza del pulsante "Back to Project" */
}

.analysis-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 1rem;
}

.analysis-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background-color: #ffffff;
  border: 1px solid #ddd;
  border-radius: 8px;
}

.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 1rem;
  background-color: #f0f0f0;
}

.bottom-toolbar {
  margin-top: auto;
}

.toolbar-buttons {
  display: flex;
  gap: 0.5rem;
}

.btn {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  transition: background-color 0.3s;
}

.icon-btn {
  background-color: #4CAF50;
  color: white;
}

.icon-btn:hover {
  background-color: #45a049;
}

.analysis-text {
  flex: 1;
  padding: 1rem;
  overflow-y: auto;
  font-size: 1rem;
  line-height: 1.6;
}

.loading {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-size: 1.2rem;
  color: #666;
}

.toolbar-message {
  position: fixed;
  bottom: 1rem;
  left: 50%;
  transform: translateX(-50%);
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  font-size: 0.9rem;
  z-index: 1000;
}

.markdown-rendered {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  text-align: left;
}

.markdown-rendered * {
  text-align: left;
}

.loading-spinner {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
}

.spinner {
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>