<template>
  <div class="project-view" v-if="project">
    <div class="top-nav">
      <button @click="goToDashboard" class="btn">Dashboard</button>
    </div>

    <div class="project-info">
      <input v-model="project.title" class="project-title" @input="enableUpdate" />
      <textarea v-model="project.description" class="project-description" @input="enableUpdate"></textarea>
    </div>

    <div class="update-btn-container">
      <button @click="updateProject" :disabled="!isUpdateEnabled" class="btn update-btn">Update</button>
      <span v-if="updateMessage" class="tooltip">{{ updateMessage }}</span>
    </div>

    <div class="mental-space-container">
      <div class="toolbar top-toolbar">
        <span class="toolbar-label">Mental Space Lattice</span>
        <div class="toolbar-buttons">
          <button class="btn" disabled>Upload Doc</button>
          <button class="btn" disabled>Acquire Viewpoint</button>
        </div>
      </div>

      <textarea v-model="project.mental_space_lattice" class="mental-space-textarea" readonly></textarea>

      <div class="toolbar bottom-toolbar">
        <span class="toolbar-caption">generated by AI</span>
        <div class="toolbar-buttons">
          <button @click="refreshMentalSpace" class="btn">Refresh</button>
          <button @click="copyMentalSpace" class="btn">Copy</button>
        </div>
      </div>
      

      <span v-if="toolbarMessage" class="tooltip bottom-tooltip">{{ toolbarMessage }}</span>
    </div>


  </div>
  <div v-else>Loading project...</div>
</template>

<script>
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import axios from 'axios';
import '../styles/ProjectView.css';

export default {
  name: 'ProjectView',
  setup() {
    const route = useRoute();
    const router = useRouter();
    const project = ref(null);
    const isUpdateEnabled = ref(false);
    const updateMessage = ref('');
    const toolbarMessage = ref('');

    const fetchProjectDetails = async () => {
      try {
        const projectId = route.params.id;
        const token = localStorage.getItem('token');
        const response = await axios.get(`${import.meta.env.VITE_API_URL}/projects/${projectId}`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        project.value = response.data;
      } catch (error) {
        console.error('Errore nel recupero dei dettagli del progetto:', error);
      }
    };

    const goToDashboard = () => {
      router.push('/dashboard');
    };

    const enableUpdate = () => {
      isUpdateEnabled.value = true;
    };

    const updateProject = async () => {
      try {
        const token = localStorage.getItem('token');
        await axios.put(`${import.meta.env.VITE_API_URL}/projects/${project.value.id}`, {
          title: project.value.title,
          description: project.value.description
        }, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        isUpdateEnabled.value = false;
        showUpdateMessage('Project updated successfully!');
      } catch (error) {
        console.error('Error updating project:', error);
        showUpdateMessage('Failed to update project.');
      }
    };

    const refreshMentalSpace = async () => {
      await fetchProjectDetails();
      showToolbarMessage('Mental space refreshed!');
    };

    const copyMentalSpace = () => {
      navigator.clipboard.writeText(project.value.mental_space_lattice)
        .then(() => showToolbarMessage('Copied to clipboard!'))
        .catch(() => showToolbarMessage('Failed to copy.'));
    };

    const showUpdateMessage = (message) => {
      updateMessage.value = message;
      setTimeout(() => {
        updateMessage.value = '';
      }, 3000);
    };

    const showToolbarMessage = (message) => {
      toolbarMessage.value = message;
      setTimeout(() => {
        toolbarMessage.value = '';
      }, 3000);
    };

    onMounted(fetchProjectDetails);

    return {
      project,
      isUpdateEnabled,
      updateMessage,
      toolbarMessage,
      goToDashboard,
      enableUpdate,
      updateProject,
      refreshMentalSpace,
      copyMentalSpace
    };
  }
};
</script>